print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/jattboy408/Desktop/backyardheros/TowerDefence_2/Assets/Animations/ranger_stance_idle_BAKED_v2.ma"`)
{		
	file -o "/Users/jattboy408/Desktop/backyardheros/TowerDefence_2/Assets/Animations/ranger_stance_idle_BAKED_v2.ma";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/jattboy408/Desktop/backyardheros/TowerDefence_2/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/jattboy408/Desktop/backyardheros/TowerDefence_2/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/jattboy408/Desktop/backyardheros/TowerDefence_2/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
